version: '3.9'

services:
  web:
    build: .
    volumes:
      - ./var/www/html/
    ports:
      - "8085:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: sistema_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sistema
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sistema.sql/docker-entrypoint-initdb.d/sistema.sql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: sistema_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      MYSQL_ROOT_PASSWORD: rootpass

    depends_on:
      -db

volumes:
  mysql_data: